// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp9NNTlIRwWcpfEK8Xy51hT2nh0YCkLxA',
    appId: '1:544357925607:web:your_web_app_id',
    messagingSenderId: '544357925607',
    projectId: 'macromate-55971',
    authDomain: 'macromate-55971.firebaseapp.com',
    storageBucket: 'macromate-55971.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp9NNTlIRwWcpfEK8Xy51hT2nh0YCkLxA',
    appId: '1:544357925607:android:ef10da4184fd696bd69842',
    messagingSenderId: '544357925607',
    projectId: 'macromate-55971',
    storageBucket: 'macromate-55971.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWyfBuyPIPfw3UACCDJAXLjUDK0h8njmc',
    appId: '1:544357925607:ios:546d3f3d8f7c1d70d69842',
    messagingSenderId: '544357925607',
    projectId: 'macromate-55971',
    storageBucket: 'macromate-55971.firebasestorage.app',
    iosBundleId: 'com.nutri.nutriApp',
  );
}
